name: Upload and download test on test-pypi
on:
  workflow_dispatch:
  pull_request:

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '^3.7, <3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-dynamic-versioning twine

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish -r test-pypi --build --username $TWINE_USERNAME --password $TWINE_PASSWORD

  download_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '^3.7, <3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install from test-pypi
      env:
        url: https://test.pypi.org/simple/derm_tiff
      run: |
        python -m pip install --index-url $url